<?php

// Pecoonia configurations.

return [
    'transaction_fields' => [
        'transaction_type'                         => [
                                                        'display_name'  =>'Transaction Type',
                                                        'sell'          => true,
                                                        'buy'           => true,
                                                        'dividend'      => true,
                                                        'cash_deposit'  => true,
                                                        'cash_withdraw' => true,
                                                        'bookvalue'     => true,
                                                        'sort_order'    => 7,
                                                    ],
        'buy_or_sell'                              => [
                                                        'display_name'  =>'Buy/Sell',
                                                        'sell'          => true,
                                                        'buy'           => true,
                                                        'sort_order'    => 8,
                                                    ],
        'inventory'                                => [
                                                        'display_name'  =>'Inventory',
                                                        'sell'          => true,
                                                        'bookvalue'     => true,
                                                    ],
        'book_value'                               => [
                                                        'display_name'  =>'Cur. book value',
                                                        'bookvalue'     => true,
                                                        'is_bookvalue_field' => true,
                                                    ],
        'trade_value'                              => [
                                                        'display_name'  =>'Trade Value',
                                                        'cash_deposit'  => true,
                                                        'cash_withdraw' => true,
                                                    ],
        'local_currency_rate'                      => [
                                                        'display_name' =>'Currency Rate',
                                                        'sell'         => true,
                                                        'buy'          => true,
                                                        'dividend'     => true,
                                                        'bookvalue'    => true,
                                                        'is_currency_rate_field' => true,
                                                    ],
        'quantity'                                 => [
                                                        'display_name' =>'Quantity',
                                                        'bookvalue'     => true,
                                                        'sell'         => true,
                                                        'is_non_decimal_field' => true,
                                                    ],
        'original_quantity'                        => [
                                                        'display_name' =>'Quantity',
                                                        'buy'          => true,
                                                        'is_non_decimal_field' => true,
                                                    ],
        'date'                                     => [
                                                        'display_name' =>'Date',
                                                        'sell'          => true,
                                                        'buy'           => true,
                                                        'dividend'      => true,
                                                        'cash_deposit'  => true,
                                                        'cash_withdraw' => true,
                                                        'bookvalue'     => true,
                                                        'is_date_field' => true,
                                                    ],
        'text'                                     => [
                                                        'display_name'  =>'Text',
                                                        'cash_deposit'  => true,
                                                        'cash_withdraw' => true,
                                                    ],
        'c_commision_local'                        => [
                                                        'display_name'     =>'Commision',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                        'buy'              => true,
                                                    ],
        'c_commision_base'                         => [
                                                        'display_name' =>'Commision',
                                                        'sell'         => true,
                                                        'buy'          => true,
                                                    ],
        'c_trade_value_local'                      => [
                                                        'display_name'     =>'Trade Value',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                        'buy'              => true,
                                                    ],
        'c_trade_value_base'                       => [
                                                        'display_name' =>'Trade Value',
                                                        'sell'         => true,
                                                        'buy'          => true,
                                                    ],
        'c_trade_quote_local'                      => [
                                                        'display_name'     =>'Price',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                        'buy'              => true,
                                                    ],
        'c_trade_quote_base'                       => [
                                                        'display_name' =>'Price',
                                                        'sell'         => true,
                                                        'buy'          => true,
                                                    ],
        'c_trade_quote_commision_local'            => [
                                                        'display_name'     =>'Price w/o commision',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                        'buy'              => true,
                                                    ],
        'c_trade_quote_commision_base'             => [
                                                        'display_name' =>'Price w/o commision',
                                                        'sell'         => true,
                                                        'buy'          => true,
                                                    ],
        'c_purchase_value_local'                   => [
                                                        'display_name'     =>'Purchase Value',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                    ],
        'c_purchase_value_base'                    => [
                                                        'display_name' =>'Purchase Value',
                                                        'sell'         => true,
                                                    ],
        'c_book_value_local'                       => [
                                                        'display_name'     =>'Book Value local',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                        'bookvalue'        => true,
                                                        'is_bookvalue_field' => true,
                                                    ],
        'c_book_value_base'                        => [
                                                        'display_name' =>'Book Value base',
                                                        'sell'         => true,
                                                        'bookvalue'    => true,
                                                        'is_bookvalue_field' => true,
                                                    ],
        'c_purchase_price_local'                   => [
                                                        'display_name'     =>'Purchase Price',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                    ],
        'c_purchase_price_base'                    => [
                                                        'display_name' =>'Purchase Price',
                                                        'sell'         => true,
                                                    ],
        'c_book_price_local'                       => [
                                                        'display_name'     =>'Book Price',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                        'is_bookvalue_field' => true,
                                                    ],
        'c_book_price_base'                        => [
                                                        'display_name' =>'Book Price',
                                                        'sell'         => true,
                                                        'is_bookvalue_field' => true,
                                                    ],
        'c_purchase_currency_rate'                 => [
                                                        'display_name' =>'Purchase Currency Rate',
                                                        'sell'         => true,
                                                        'is_currency_rate_field' => true,
                                                        'hide_if_sec_curr_eq_base_curr' => true,
                                                    ],
        'c_book_currency_rate'                     => [
                                                        'display_name' =>'Book Currency Rate',
                                                        'sell'         => true,
                                                        'is_bookvalue_field' => true,
                                                        'is_currency_rate_field' => true,
                                                        'hide_if_sec_curr_eq_base_curr' => true,
                                                    ],
        'c_profit_loss_book_value_local'           => [
                                                        'display_name'     =>'Profit/Loss Book Value',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                        'is_bookvalue_field' => true,
                                                    ],
        'c_profit_loss_book_value_base'            => [
                                                        'display_name' =>'Profit/Loss Book Value',
                                                        'sell'         => true,
                                                        'is_bookvalue_field' => true,
                                                    ],
        'c_profit_loss_purchase_value_local'       => [
                                                        'display_name'     =>'Profit/Loss Purchase Value',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                    ],
        'c_profit_loss_purchase_value_base'        => [
                                                        'display_name' =>'Profit/Loss Purchase Value',
                                                        'sell'         => true,
                                                    ],
        'c_profit_loss_purchase_value_lc_account'  => [
                                                        'display_name' =>'Profit/Loss Purchase Value 2',
                                                        'sell'         => true,
                                                        'hide_if_sec_curr_eq_base_curr' => true,
                                                    ],
        'c_return_purchase_value_local'            => [
                                                        'display_name'     =>'Return Purchase Value',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                        'add_percentage_sign' => true,
                                                    ],
        'c_return_purchase_value_base'             => [
                                                        'display_name' =>'Return Purchase Value',
                                                        'sell'         => true,
                                                        'add_percentage_sign' => true,
                                                    ],
        'c_return_book_value_local'                => [
                                                        'display_name'     =>'Return Book Value',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                        'is_bookvalue_field' => true,
                                                        'add_percentage_sign' => true,
                                                    ],
        'c_return_book_value_base'                 => [
                                                        'display_name'     =>'Return Book Value',
                                                        'sell'             => true,
                                                        'is_bookvalue_field' => true,
                                                        'add_percentage_sign' => true,
                                                    ],
        'c_currency_profit_loss_book_value'        => [
                                                        'display_name' =>'Currency Profit/Loss Book Value',
                                                        'sell'         => true,
                                                        'is_bookvalue_field' => true,
                                                        'hide_if_sec_curr_eq_base_curr' => true,
                                                    ],
        'c_currency_profit_loss_purchase_price'    => [
                                                        'display_name' =>'Currency Profit/Loss Purchase Value',
                                                        'sell'         => true,
                                                        'hide_if_sec_curr_eq_base_curr' => true,
                                                    ],
        'c_profit_loss_book_value_excurrency'      => [
                                                        'display_name' =>'Profit/Loss Book Value ex. currency',
                                                        'sell'         => true,
                                                        'is_bookvalue_field' => true,
                                                        'hide_if_sec_curr_eq_base_curr' => true,
                                                    ],
        'c_profit_loss_purchase_price_excurrency'  => [
                                                        'display_name' =>'Profit/Loss Purchase Value ex. currency',
                                                        'sell'         => true,
                                                        'hide_if_sec_curr_eq_base_curr' => true,
                                                    ],
        'c_average_purchase_price'                 => [
                                                        'display_name' =>'Average Purchase Price',
                                                        'sell'         => true,
                                                    ],
        'c_average_profit_loss_purchase_price'     => [
                                                        'display_name' =>'Profit/Loss Average Purchase Price',
                                                        'sell'         => true,
                                                    ],
        'c_average_days_owned'                     => [
                                                        'display_name' =>'Average Days Owned',
                                                        'sell'         => true,
                                                        'is_non_decimal_field' => true,
                                                    ],
        'c_daily_profit_loss_purchase_value_local' => [
                                                        'display_name'     =>'Daily Profit/Loss Purchase Value',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                    ],
        'c_daily_profit_loss_purchase_value_base'  => [
                                                        'display_name' =>'Daily Profit/Loss Purchase Value',
                                                        'sell'         => true,
                                                    ],
        'c_daily_return_purchase_value_local'      => [
                                                        'display_name'     =>'Daily Return Purchase Value',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                        'add_percentage_sign' => true,
                                                    ],
        'c_daily_return_purchase_value_base'       => [
                                                        'display_name' =>'Daily Return Purchase Value',
                                                        'sell'         => true,
                                                        'add_percentage_sign' => true,
                                                    ],
        'c_annualized_return_purchase_value_local' => [
                                                        'display_name'     =>'Annualized Return Purchase Value',
                                                        'display_currency' => true,
                                                        'sell'             => true,
                                                        'add_percentage_sign' => true,
                                                    ],
        'c_annualized_return_purchase_value_base'  => [
                                                        'display_name' =>'Annualized Return Purchase Value',
                                                        'sell'         => true,
                                                        'add_percentage_sign' => true,
                                                    ],
        'c_dividend_local'                         => [
                                                        'display_name'     =>'Dividend local',
                                                        'display_currency' => true,
                                                        'dividend'         => true,
                                                    ],
        'c_dividend_base'                          => [
                                                        'display_name' =>'Dividend base',
                                                        'dividend'     => true,
                                                    ],
        'c_net_dividend_local'                     => [
                                                        'display_name'     =>'Net Dividend local',
                                                        'display_currency' => true,
                                                        'dividend'         => true,
                                                    ],
        'c_net_dividend_base'                      => [
                                                        'display_name' =>'Net Dividend base',
                                                        'dividend'     => true,
                                                    ],
        'c_tax_local'                              => [
                                                        'display_name'     =>'Tax',
                                                        'display_currency' => true,
                                                        'dividend'         => true,
                                                    ],
        'c_tax_base'                               => [
                                                        'display_name' =>'Tax',
                                                        'dividend'     => true,
                                                    ],
        'tags'                                     => [
                                                        'display_name' =>'Tags',
                                                        'sell'         => true,
                                                        'buy'          => true,
                                                    ],
        'security_name'                            => [
                                                        'display_name' =>'Security',
                                                        'sell'         => true,
                                                        'buy'          => true,
                                                        'dividend'     => true,
                                                        'bookvalue'    => true,
                                                        'sort_order'   => 2,
                                                    ],
        'security_symbol'                          => [
                                                        'display_name' =>'Symbol',
                                                        'sell'         => true,
                                                        'buy'          => true,
                                                        'dividend'     => true,
                                                        'bookvalue'    => true,
                                                        'sort_order'   => 3,
                                                    ],
        'bank_name'                                => [
                                                        'display_name'  =>'Bank Account',
                                                        'sell'          => true,
                                                        'buy'           => true,
                                                        'dividend'      => true,
                                                        'cash_deposit'  => true,
                                                        'cash_withdraw' => true,
                                                        'sort_order'    => 1,
                                                    ],
        'security_type'                            => [
                                                        'display_name' =>'Security Type',
                                                        'sell'         => true,
                                                        'buy'          => true,
                                                        'dividend'     => true,
                                                        'sort_order'   => 5,
                                                    ],
        'security_exchange'                        => [
                                                        'display_name' =>'Exchange',
                                                        'sell'         => true,
                                                        'buy'          => true,
                                                        'dividend'     => true,
                                                        'sort_order'   => 4,
                                                    ],
        'security_currency'                        => [
                                                        'display_name'  =>'Currency',
                                                        'sell'          => true,
                                                        'buy'           => true,
                                                        'dividend'      => true,
                                                        'cash_deposit'  => true,
                                                        'cash_withdraw' => true,
                                                        'bookvalue'     => true,
                                                        'sort_order'    => 6,
                                                    ],
    ],
    'transaction_types' => [
        'cash_deposit' => [
            'display_name' =>'Cash',
        ],
        'cash_withdraw' => [
            'display_name' =>'Cash',
        ],
        'sell' => [
            'display_name' =>'Security',
        ],
        'buy' => [
            'display_name' =>'Security',
        ],
        'dividend' => [
            'display_name' =>'Dividend',
        ],
        'bookvalue' => [
            'display_name' =>'Book Value',
        ],
    ],
    'yahoo_security_fields' => [
        'symbol',
        'AverageDailyVolume',
        'Change_PercentChange',
        'Change',
        'Currency',
        'LastTradeDate',
        'LastTradePriceOnly',
        'DaysLow',
        'DaysHigh',
        'YearLow',
        'YearHigh',
        'DaysRange',
        'Name',
        'Volume',
        'StockExchange',
        'LastTradeTime',
        'MarketCapitalization',
        'Open',
        'PreviousClose'
    ],
    'portfolio_guideline_types' => [
        'cash_allocation'          => [ 'label' => 'Cash allocation',
                                        'desc'  => 'Guideline that defines the amount cash should comprise of the Total Portfolio value.'],
        'securities_in_portfolio'  => ['label' => 'Securities in portfolio',
                                       'desc'  => 'Guideline that defines how many securities the portfolio should comprise of.'],
        'risc_per_position'        => ['label' => 'Risc per position',
                                       'desc'  => 'Guideline that defines how big a (potential) loss a single position can have relative to the Total Portfolio value.'],
        'currency_allocation'      => ['label' => 'Currency allocation',
                                       'desc'  => 'Guideline that defines how much securities with a specific currency should comprise relative to the Total Portfolio value.'],
        'security_type_allocation' => ['label' => 'Security type allocation',
                                       'desc'  => 'Guideline that defines how much a specific security type should comprise relative to the Total Portfolio value.'],
        'weight_per_position'      => ['label' => 'Weight per position',
                                       'desc'  => 'Guideline that defines how much a single security position can weigh relative to the value of all securities (Total Market Value).'],
        'tag_allocation'           => ['label' => 'Tag allocation',
                                       'desc'  => 'Guideline that defines how much securities with a specific tag should comprise relative to the Total Portfolio value.']
    ],
];